# Generated by Django 4.1.7 on 2023-03-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('in Stock', 'in Stock')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
