# Generated by Django 4.1.7 on 2023-03-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogs/%Y/%m/%d'),
        ),
    ]
